In [1]:
# Data Abstraction 

In [1]:
#from abc import ABC, abstractmethod
from abc import abstractmethod
from abc import ABC

In [4]:
class Sample(ABC):
    def Abs_method(self):
        pass
class child(Sample):
    def Abs_method(self):
        print("Abstraction")
    
obj=child()
obj.Abs_method()

Abstraction


In [5]:
# Method Overriding
class Sample(ABC):
    def Abs_method(self):
        print("Welcome")
class child(Sample):
    def Abs_method(self):
        print("Abstraction")
    
obj=child()
obj.Abs_method()

Abstraction


In [7]:
# Concrete Method 
class Sample(ABC):
    def Abs_metho d(self):
        print("Welcome")
class child(Sample):
    def Abs_method(self):
        super().Abs_method() # super().Method/function name 
        print("Abstraction")
    
obj=child()
obj.Abs_method()

Welcome
Abstraction


In [18]:
# Recursion

In [8]:
def Fact(n):
    if n==1:
        return 1
    else:
        return (n*Fact(n-1))

num=int(input("Enter the value:"))
print(Fact(num))

Enter the value:3
6


In [20]:
# NumPy
#DATA MANIPULTION --PROCESS OF CONVERTING DATA INTO A SUITABLE FORMAT THAT'S IS FOR THE EASY TO PROCESS AND MORE ORGANIZED

In [24]:
import numpy

In [32]:
import numpy as np

In [12]:
# array1=np.array([10,20,30,40,50])
# print(array1)
# print(type(array1))

array1 =np.array([10,20,30,40])
print(array1)
print(type(array1))  


[10 20 30 40]
<class 'numpy.ndarray'>


In [11]:

array2=np.array((10,20,30,40,50))
print(array2)
print(type(array2))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [14]:
a3=np.array(10) # Zero Dimentions
print(a3)
print(type(a3))

10
<class 'numpy.ndarray'>


In [37]:
array2=np.array((10,20,30,40,50)) # One - Dimetions
print(array2)

[10 20 30 40 50]


In [15]:
a4=np.array(([1,2],[3,4],[5,6])) # 2 or multi
print(a4)

[[1 2]
 [3 4]
 [5 6]]


In [73]:
a4=np.array(([1,2,10],[3,4,20],[5,6,40]))
print(a4)

[[ 1  2 10]
 [ 3  4 20]
 [ 5  6 40]]


In [16]:
np.full((2,2),5)  # Full 
#pratice
np.full((3,2),4)

array([[4, 4],
       [4, 4],
       [4, 4]])

In [41]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [43]:
# Arange
np.arange(20,50,5) # 10-25 ---  5 intervals 

array([20, 25, 30, 35, 40, 45])

In [47]:
# linspace
np.linspace(5,10,5)   #x, y , z #
# z(6 & 5)  # x(5) # y(10)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [48]:
# Array Inspection

In [49]:
# ndarray.shape

In [50]:
n= np.array(([10,20,30],[40,50,60]))
print(n.shape)

(2, 3)


In [51]:
n= np.array(([10,20,30],[40,50,60],[80,90,100]))
print(n.shape)

(3, 3)


In [53]:
n= np.array(([9.5,3.5,3],[6,5,6],[8,10,11],[9.3,8.8,1.0]))
print(n.shape)

(4, 3)


In [57]:
n= np.array(([1,2],[0.7,9.6],[2.5,8.9]))
print(n.shape)

(3, 2)


In [33]:
n= np.array(([1,2],[0.7,9.6],[2.5,8.9]))
n.shape=(3,2)
print(n)
print(n.ndim) 

[[1.  2. ]
 [0.7 9.6]
 [2.5 8.9]]
2


In [65]:
# Size
n=np.arange(30)
print(n.size)

30


In [66]:
# Dimention -ndim
print(a3.ndim)
print(array2.ndim)
print(a4.ndim)

0
1
2


In [20]:
# Dtype
print(a4.dtype) 

int64


In [30]:
# mathematics 
# np.sum(a,b)
# np.subtract(a,b)
# np.divide(a,b)
# np.multiply(a,b)
# np.exp(a)
# np.sqrt(a)
# np.sin(a)
# np.cos(a)
# np.log(a)


a = int(input("enter the value of a"))
b = int(input("enter the value of b"))
# np.sum([a,b])
np.subtract(a, b)


enter the value of a20
enter the value of b10


10

In [70]:
np.sum([10,12]) # addition

22

In [34]:
a=int(input("Enter the value:"))
b=int(input("Enter the value:"))
np.sum([a,b])

Enter the value:10
Enter the value:20


30